export const CREATURES = {
  Flameling: {
    name: 'Flameling',
    type: 'Fire',
    color: '#ff8759',
    baseHp: 26,
    baseAttack: 7,
    baseDefense: 5,
    baseSpeed: 6,
    moves: ['scratch', 'ember'],
  },
  Mosshell: {
    name: 'Mosshell',
    type: 'Leaf',
    color: '#7fc65a',
    baseHp: 30,
    baseAttack: 6,
    baseDefense: 7,
    baseSpeed: 4,
    moves: ['tackle', 'vine-whip'],
  },
  Tidepaw: {
    name: 'Tidepaw',
    type: 'Water',
    color: '#63b7ff',
    baseHp: 28,
    baseAttack: 6,
    baseDefense: 6,
    baseSpeed: 6,
    moves: ['pounce', 'splash-burst'],
  },
  Pebblit: {
    name: 'Pebblit',
    type: 'Stone',
    color: '#c2a47f',
    baseHp: 32,
    baseAttack: 7,
    baseDefense: 8,
    baseSpeed: 3,
    moves: ['bump', 'stone-toss'],
  },
  Zephyroo: {
    name: 'Zephyroo',
    type: 'Wind',
    color: '#e7f0ff',
    baseHp: 24,
    baseAttack: 8,
    baseDefense: 4,
    baseSpeed: 9,
    moves: ['peck', 'gust'],
  },
};
